version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Instead of hardcoding variables, we load them from backend/.env
    env_file:
      - ./backend/.env
    # The container will read MONGO_URI, JWT_SECRET, EMAIL_USER, etc., from that file.

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://51.20.31.138:5000
    depends_on:
      - backend
